# Set maxretry to 3 by default, this should mitigate race with slow devices:
maxretry = 3
pollinterval = 5

[cps]
    driver = usbhid-ups
    port = auto
    vendorid = 0764
    desc = "CyberPower EC850LCD"
    offdelay = 60
    ondelay = 120
    ignorelb
    override.battery.charge.low = 40
    override.battery.runtime.low = 600
